language: shell

# Doc
# - Travis Job Lifecycle : https://docs.travis-ci.com/user/job-lifecycle/

jobs:
  include:
#    - name: "Guideline checks"
#      os: linux
#      dist: xenial
#      compiler: clang
#      env:
#        - BUILD_NAME="checks"
#
#    - name: "Linux Debug"
#      os: linux
#      dist: xenial
#      env:
#        - BUILD_NAME="linux-macos"
#        - MODE=Debug
#      addons:
#        apt:
#          packages:
#            - liblapack-dev
#
#    - name: "Linux Release"
#      os: linux
#      dist: xenial
#      env:
#        - BUILD_NAME="linux-macos"
#        - MODE=Release
#      addons:
#        apt:
#          packages:
#            - liblapack-dev
#
#    - name: "MacOS Debug"
#      os: osx
#      osx_image: xcode9.4
#      env:
#        - BUILD_NAME="linux-macos"
#        - MODE=Debug
#
#    - name: "Windows Debug"
#      os: windows
#      env:
#        - BUILD_NAME="windows"
#        - MODE=Debug
#
##    - name: "Windows Release"
##      os: windows
##      env:
##        - BUILD_NAME="windows"
##        - MODE=Release
#
#    - name: "Linux Coverage"
#      os: linux
#      dist: xenial
#      compiler: clang
#      env:
#        - BUILD_NAME="linux-macos"
#        - MODE=Coverage
#      addons:
#        apt:
#          update: true
#          packages:
#            - liblapack-dev
#            - lcov
#
##    # Disabled because too long
##    - name: "MacOS Coverage"
##      os: osx
##      osx_image: xcode9.4
##      env:
##        - BUILD_NAME="linux-macos-coverage"
##        - MODE=Coverage
##      addons:
##        homebrew:
##          update: true
##          packages:
##            - lcov
#
#    - name: "Octave Linux"
#      os: linux
#      dist: bionic # bionic does not support Octave 5
#      env:
#        - BUILD_NAME="octave-linux-macos"
#      addons:
#        apt:
#          packages:
#            - octave
#            - octave-pkg-dev
#
#    - name: "Octave MacOS"
#      os: osx
#      osx_image: xcode9.4
#      env:
#        - BUILD_NAME="octave-linux-macos"
#
##    - name: "Octave Windows"
##      os: windows
##      env:
##        - BUILD_NAME="octave-windows"

    - name: "R Linux"
      os: linux
      dist: xenial
      env:
        - BUILD_NAME="r-linux-macos"
        - MODE=Release
      language: r
      r: release

    - name: "R MacOS"
      os: osx
      osx_image: xcode9.4
      env:
        - BUILD_NAME="r-linux-macos"
        - MODE=Release
      language: r
      r: release

    - name: "R Windows"
      os: windows
      env:
        - BUILD_NAME="r-windows"
        - MODE=Release

install:
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/install.sh

before_script:
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/before_script.sh

script:
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/build.sh
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/test.sh

#addons:
#  artifacts:
#    debug: false
#    paths:
#      - ${HOME}/build

after_success:
  - ${TRAVIS_BUILD_DIR}/.travis-ci/${BUILD_NAME}/after_success.sh
  # pre-deploy cannot neither be in after_script which is the last script (after deploy), 
  # nor in before_deploy since the condition is checked before *deploy scripts    
  - "${TRAVIS_BUILD_DIR}/.travis-ci/release/pre-deploy.sh"
  - "[ -e ${TRAVIS_BUILD_DIR}/DEPLOY_FILE ] && export DEPLOY_FILE=$(cat ${TRAVIS_BUILD_DIR}/DEPLOY_FILE)"
  - "[ $DEBUG_CI = true ] && echo DEPLOY_FILE=$DEPLOY_FILE"

deploy:
  provider: releases
  api_key: $API_DEPLOY_TOKEN
  file: $DEPLOY_FILE
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
    repo: libKriging/libKriging
    condition: $MODE = "Release" && -e $DEPLOY_FILE

# Cache update/upload is too slow and slow down the whole process
#cache:
#  directories:
#  - bindings/R/Rlibs
#  - $HOME/Miniconda3
#  - /c/Rtools

env:
  global: 
    - DEBUG_CI=true